### ISSUE TITLE
Nothing shown on debug

### ISSUE THREAD

**Issue by cbscpe2** [dirkjanfaber/node-red-contrib-victron-vedirect-usb#2]
I thought I just tried this but had no Victron Cable at hand, so I took another one from Prolific Technology Inc. with an ADUM1201 isolation to make sure I do not kill anything. I edited vedirect-usb.js restarted Node Red and indeed the cable showed in the port list of the node. I added an inject node and a debug node. Immediately the node showed the correct model, but when I activate inject nothing spectacular happens on the debug, i.e. only the following is shown
`9.5.2023, 14:33:04[node: debug 17](http://192.168.173.122:1880/#)
msg : Object
{ _msgid: "af976c52d773b6b1", payload: object, topic: "" }`

I made a screenshot from the flow, where you can clearly see the green dot and the correctly identified model

<img width="765" alt="Bildschirmfoto 2023-05-09 um 14 39 41" src="https://github.com/dirkjanfaber/node-red-contrib-victron-vedirect-usb/assets/66900217/2a7feffd-286a-4de3-9d94-15eb149dd843">

What am I missing?

**Comment by cbscpe2** [comment]
sorry for that, I was really missing something, namely to open the attached object to display the content, shame on me.

**Comment by dirkjanfaber** [comment]
Glad that it works. I'll close the issue then.

**Comment by cbscpe2** [comment]
Yes of course, thanks and sorry for the trouble.
