### ISSUE TITLE
Remove or add to USB Filter

### ISSUE THREAD

**Issue by stueng** [dirkjanfaber/node-red-contrib-victron-vedirect-usb#4]
Hi, would like to use your Node red module, however the USB filter is causing a problem. I have a third party isolated, quad UART to single USB board from [dupa.it](https://www.duppa.net/shop/ve-direct-jst-cable/) so the filter is making it so that I cant use the module. Is there a way to remove or amend the filter to include this device?

lsusb shows:

Bus 001 Device 003: ID 0403:6011 Future Technology Devices International, Ltd FT4232H Quad HS USB-UART/FIFO IC

**Comment by dirkjanfaber** [comment]
For testing you can remove line 54 and 56 from the `vedirect-usb.js`  file:

https://github.com/dirkjanfaber/node-red-contrib-victron-vedirect-usb/blob/8e2cdf6c9f1a80599926d97c168a7753d53a4111/src/nodes/vedirect-usb.js#L54

https://github.com/dirkjanfaber/node-red-contrib-victron-vedirect-usb/blob/8e2cdf6c9f1a80599926d97c168a7753d53a4111/src/nodes/vedirect-usb.js#L56

I'll try to release a new version that gets an option for disabling filtering in a few days, but no promises.

**Comment by stueng** [comment]
thanks, I have worked around it by importing JSON with the TTY populated

**Comment by dirkjanfaber** [comment]
Fixed in release 0.1.3
